name: Run Tests on Push

on:
  push:
    branches:
      - '**'  # Triggers on push to any branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Run Tests with Maven
        run: mvn test
